# controllers:
#     resource: ../src/Controller/
#     type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

api_login_check:
    path: /api/login_check

app_logout:
    path: /logout

api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: POST

etudiant:
    path: /api/etudiant
    controller: App\Controller\ProfilController::etudiant
    methods: GET

competences:
    path: /api/competences
    controller: App\Controller\CompetencesController::competences
    methods: GET

utilisateur:
    path: /api/utilisateur
    controller: App\Controller\UtilisateurController::utilisateur
    methods: GET

utilisateurprojet:
    path: /api/utilisateurprojet
    controller: App\Controller\UtilisateurController::utilisateurprojet
    methods: GET

prof:
    path: /prof
    controller: App\Controller\ProfilController::prof

addprojet:
    path: /addprojet
    controller: App\Controller\AddprojetController::formProjet

portfolioall:
    path: /api/portfolio
    controller: App\Controller\ProjetController::allprojet
    methods: GET

portfoliosinlge:
    path: /api/portfolio/{id}
    controller: App\Controller\ProjetController::projet
    methods: GET

# portfoliosingle:
#     path: /portfolio/{id}
#     controller: App\Controller\PortfolioController::afficheProjetUtilisateur

admin:
    path: /admin
    controller: App\Controller\ProfilController::admin

api_delete_user:
    path: api/deleteuser/{id}
    controller: App\Controller\DeleteController::delete
    methods: DELETE

api_delete_projet:
    path: api/deleteprojet/{id}
    controller: App\Controller\DeleteController::deleteprojet
    methods: DELETE

api_delete_comm:
    path: api/deletecomm/{id}
    controller: App\Controller\DeleteController::deletecomm
    methods: DELETE

api_profil:
    path: api/username/{email}
    controller: App\Controller\UtilisateurController::getusername
    methods: GET

commentaire:
    path: api/commentaire
    controller: App\Controller\CommentaireController::commentaire
    methods: GET

api_addCommentaire:
    path: api/addCommentaire
    controller: App\Controller\CommentaireController:addCommentaire
    methods: POST

app.swagger:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }