# controllers:
#     resource: ../src/Controller/
#     type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

api_login_check:
    path: /api/login_check

app_logout:
    path: /logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register


etudiant:
    path: /api/etudiant
    controller: App\Controller\ProfilController::etudiant
    methods: GET

# accueil:
#     path: /accueil
#     controller: App\Controller\HomeController::accueil

prof:
    path: /prof
    controller: App\Controller\ProfilController::prof

admin:
    path: /admin
    controller: App\Controller\ProfilController::admin

app.swagger:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }